#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
número = int(input('Digite um número para ver a sua tabuada: '))
print('-'*15)
print('{} x {:2} = {}'.format(número, 0, número*0))
print('{} x {:2} = {}'.format(número, 1, número*1))
print('{} x {:2} = {}'.format(número, 2, número*2))
print('{} x {:2} = {}'.format(número, 3, número*3))
print('{} x {:2} = {}'.format(número, 4, número*4))
print('{} x {:2} = {}'.format(número, 5, número*5))
print('{} x {:2} = {}'.format(número, 6, número*6))
print('{} x {:2} = {}'.format(número, 7, número*7))
print('{} x {:2} = {}'.format(número, 8, número*8))
print('{} x {:2} = {}'.format(número, 9, número*9))
print('{} x {} = {}'.format(número, 10, número*10))
print('-'*15)
